### ISSUE TITLE
Simplification ideas for site aliases and backend.inc

### ISSUE THREAD

**Issue by weitzman** [drush-ops/drush#975]
- [ ] Remove concurrency
- [ ] Remove shell alias replacements, e.g. `{{@target}}` - #1369.
- [ ] Remove site alias lists, e.g. `@foo,@bar`
- [x] Remove 'parent' inheritance in site aliases - #1279
- [x] Remove relative aliases @site/@peer. https://github.com/drush-ops/drush/commit/db8166def32e64b2c75b10dc884eddaa5f1b5c03 
- [x] Add [an alter hook](http://api.drush.org/api/drush/drush.api.php/function/hook_drush_sitealias_alter/master), so aliases can be adjusted in a [policy file](https://github.com/drush-ops/drush/blob/c129ea6ce51f6387d244f57debd04335b9c07dc1/examples/policy.drush.inc).
- [ ] Change site aliases to .yml. Dynamic changes still possible with [hook_sitealias_alter](http://api.drush.org/api/drush/drush.api.php/function/hook_drush_sitealias_alter/master). Segregate config, site selection (root+uri), and other parts of the array better. Replace array with one or more objects. - #1609 
- [ ] Refactor remote sites to be a first class object that gets passed around. Distinct from drush_get_option()

**Comment by greg-1-anderson** [comment]
I am thinking we should make these changes in master, after we have spun off Drush 7, rather than try to make these changes at this time.

**Comment by ergonlogic** [comment]
In Aegir and a number of related projects, we use much of backend.inc extensively. I'm all for simplifying it as much as possible.

In core, concurrency only appears to be used by make. We could move the relevant logic over there in a simplified manner, presumably. Are there any other projects that we know of making extensive use of concurrency (or the other proposed removals, for that matter)?

More OOP, YML and support for remote sites will benefit just about all the projects I'm working on.

**Comment by greg-1-anderson** [comment]
@juampy72 recently used concurrency in one of his projects.

**Comment by juampy72** [comment]
This command uses drush_invoke_concurrent() when GNU-parallel is not
available: http://drupal.org/project/syncdb.

http://drupal.org/project/concurrent_queue uses it too.

**Comment by greg-1-anderson** [comment]
I added a PR #1279 to deprecate the 'parent' element and add an alter hook.  This is a first step toward supporting YAML site alias files.

**Comment by ccharlton** [comment]
"Remove shell alias replacements" -- you mean the custom tokens like `%my_custom_thing`?

**Comment by greg-1-anderson** [comment]
@ccharlton: Yep, that's what that is.  I edited the summary to make it more clear. See also the issue number referenced above, #1369.

My general impression is that these are very rarely used; if anyone has ever written a blog post about this feature, I haven't seen it.  Similar things can be done by defining a custom shell alias directly inside the site alias.  I suspect that would be easier for most folks to understand and use.

**Comment by kenorb** [comment]
Btw. Acquia Cloud still using `parent` when exporting `x.aliases.drushrc.php` from Drush integration for the site.

Like:

	$aliases['test.livedev'] = array(
	  'parent' => '@foo.test',
	  'root' => '/mnt/foo.test/livedev/docroot',
	);

Does it mean it would break when I'll upgrade `drush`? Seems to work so far on `8.0-dev`.

**Comment by greg-1-anderson** [comment]
Although it is checked off above, 'parent' is only deprecated, not removed. We should probably make sure folks aren't using this, or have switched to a policy file, before we fully remove it from the code.

**Comment by weitzman** [comment]
Acquia puts that item in our file but it is not used.

**Comment by BarisW** [comment]
Hmm, we use it a lot in our company. All dev environments inherit a base dev alias.  

http://www.bariswanschers.com/blog/working-drush-alias-files-teams (See: Bonus tip: alias files inheritance)

**Comment by weitzman** [comment]
@BarisW - Some replacement code for @parent is in [our example policy file](https://github.com/drush-ops/drush/blob/c129ea6ce51f6387d244f57debd04335b9c07dc1/examples/policy.drush.inc)

**Comment by BarisW** [comment]
Thanks @weitzman!

**Comment by greg-1-anderson** [comment]
Mostly done; closing.
